### ISSUE TITLE
[BUG] Mutagen status is shown as disabled even though it is actually enabled

### ISSUE THREAD

**Issue by rpkoller** [biati-digital/vscode-ddev-manager#1]
Please make sure that the bug only applies to this extension, if you have a problem with ddev itself you should open an issue in the ddev repo and not here.

**Describe the bug**
The expanded running project in the VSCode sidebar shows Mutagen as disabled while it is actually shown as enabled when you check the project with for example `ddev describe` or `ddev mutagen monitor`. 
for the context the `config.yaml` files for both projects i've provided a screenshot for have nothing related to mutagen in their config.yaml files. mutagen is only set in `~/.ddev/global_config.yaml` with `performance_mode: mutagen`.

p.s thank you for working on and releasing the extension! looks really interesting and useful. 
 
**To Reproduce**
1. Start an existing project
2. Expand the project in the VSCode sidebar
4. Go to the terminal and run `ddev describe` or `ddev mutagen sync`

**Expected behavior**
I would have expected that the project in the VScode sidebar would show Mutagen as enabled

**Screenshots**
Noticed with one DDEV project set to PHP where I wanted to test something with the Drupal install process

![php](https://github.com/biati-digital/vscode-ddev-manager/assets/1665422/1eebb2db-1129-45c6-a8c2-fd374f702e2e)

But happens also on DDEV projects  explicitly declared as a Drupal project. Initially thought maybe something is off with the PHP project. 

![drupal](https://github.com/biati-digital/vscode-ddev-manager/assets/1665422/4838ca00-e74a-4245-b558-89cf6cae64c3)

**System (please complete the following information):**
 - OS: MacOS 12.6.8
 - DDEV version: vHEAD-66471cf
 - Colima version: 0.5.5 (runtime: docker, arch: aarch64, client: v24.0.5, server: v20.10.11)
 - VSCode version: 1.81.1 (Universal)

**Additional context**

**Comment by biati-digital** [comment]
Thank's for trying the extension. I've found and fixed this error. I'll publish an update soon including other improvements and fixes.

**Comment by biati-digital** [comment]
The update has bee published, please try it and let me know if it's working for you.

**Comment by rpkoller** [comment]
I've updated to the latest version and can confirm that the error is fixed. Tested with two running projects. 

![Screen Shot 2023-09-03 at 00 55 26](https://github.com/biati-digital/vscode-ddev-manager/assets/1665422/123dcc25-3b42-4734-876a-81a119c27662)

I've set the performance_mode setting to `none` for one of the projects. after restart the project's mutagen status was correctly shown as disabled (just wanted to test that it works as well the other way around. 

![Screen Shot 2023-09-03 at 00 58 56](https://github.com/biati-digital/vscode-ddev-manager/assets/1665422/45de914c-7aee-42e0-8920-762e3100ce39)

so thanks for the quick fix!

p.s.  one detail i have noticed. i have one vscode window open in the ddev manager tab with the two projects running from the screenshot. i've then opened one of the two projects in another vscode window and changed the performance mode setting there and triggered the restart. in the projects vscode window the project state as well as the mutagen status was updated properly. but the status for the two projects in the other vscode window remained running and for both projects the mutagen status remained enabled. that might be a potential stepping stone that "might" lead into issue for people that have many projects running with several vscode windows?

**Comment by biati-digital** [comment]
I'm glad it's working. 

Currently the extension does not listen to DDEV changes outside the current VSCode window, it's a must have feature and will be implemented (I totally forgot to add this to the Roadmap in the ReadMe) but I'm currently trying to figure out the best way to do it.

Thank's for trying it.
