### ISSUE TITLE
[BUG] Rename "Type" to "Project Type"

### ISSUE THREAD

**Issue by tyler36** [biati-digital/vscode-ddev-manager#3]
**Describe the bug**
Not really a bug, more of a nitpick.

DDEV uses the term "Project Type" to refer to framework being served. Eg. Drupal10, Laravel, Typo3.

For consistency with DDEV online documention and CLI messages, I suggest it be change in the tree view.

**To Reproduce**

- View a project in the extension

**Expected behavior**
Label as "Project Type"

**Screenshots**
 (screenshot copied from README)

![ddev-preview](https://github.com/biati-digital/vscode-ddev-manager/assets/7234392/6c5907ce-f569-43dd-8c05-fc8591aade33)

**System (please complete the following information):**

- OS: Win10 & WSL2
- DDEV version: `1.22.1`
- Docker provider: Docker Desktop
- VSCode version: `1.81.1`

**Additional context**

**Comment by biati-digital** [comment]
Sure, this change will be included in the next update.

**Comment by biati-digital** [comment]
A new update has been published including this change.
