### ISSUE TITLE
Highlight currently opened project in initial DDEV Manager view

### ISSUE THREAD

**Issue by ultimike** [biati-digital/vscode-ddev-manager#7]
**Is your feature request related to a problem? Please describe.**
Not a problem, but could be a small improvement. Consider the following workflow:

1. I open VSCode to my DDEV project named "stormtrooper". 
2. I click on the DDEV Manager icon in the side bar and am presented with a list of all DDEV projects on the machine.
3. The list of DDEV projects does not indicate that VSCode is currently open to the "stormtrooper" project.

**Describe the solution you'd like**
The currently opened project should be highlighted, or at the top of the list.  

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ultimike** [comment]
Oh wait - I just found the "Workspace project" toggle! I think that should be the default view, not the full list of all DDEV projects on the machine.

**Comment by biati-digital** [comment]
Hi, I'm glad you found it. I believe that using that as the default view defeats the purpose of this extension which is to be able to manage all your projects form the sidebar.

I'm sure everyone will find that toggle (to only show your workspace project) while playing with the extension for a few minutes.

There's also a setting in the VSCode extension settings page to configure if you always want to show all projects or only the current workspace project.
