### ISSUE TITLE
Better category in marketplace?

### ISSUE THREAD

**Issue by rfay** [biati-digital/vscode-ddev-manager#8]
Why is this listed in the marketplace as "testing"? It seems like it would be happier in a different category. However, looking I don't see any great ones. Maybe "other"? https://marketplace.visualstudio.com/search?target=VSCode&category=Other&sortBy=Installs

<img width="491" alt="image" src="https://github.com/biati-digital/vscode-ddev-manager/assets/112444/3079f0be-3ce7-466a-8b4c-b124e75ee284">

**Comment by tyler36** [comment]
"other" seems appropriate as it contains other Docker/like extensions.

**Comment by biati-digital** [comment]
Sure, I'm preparing an update and this change will be included.

**Comment by biati-digital** [comment]
@rfay @tyler36  Can you help me to figure out a way to solve this other issue? https://github.com/biati-digital/vscode-ddev-manager/issues/9

**Comment by tyler36** [comment]
> Can you help me to figure out a way to solve this other issue?

FYI, Discord is where a lot of the community hangs out.  Here's an invite [link](https://discord.com/channels/664580571770388500/955757711717462066/1068605994923462656).
